// question-sets/cyber-basic.js
// Cyber Security AWARENESS set for general-audience / workplace events (no prior knowledge).
// Same shape as kids-questions.js: 6 weapon categories, 12 each, `a:0` correct (server
// shuffles), `e` explains after every answer. `meta.topics` relabels the weapon cards.
// Content is defensive / good-practice only.

module.exports = {

  meta: {
    title: 'Cyber Basics',
    topics: {
      flipper: 'Passwords & Logins',
      pit: 'Phishing & Scams',
      spinner1: 'Safe Browsing',
      spinner2: 'Devices & Updates',
      spinner3: 'Data & Privacy',
      mega: 'Boss: Staying Safe'
    }
  },

  // ---------- Flipper: Passwords & Logins ----------
  flipper: [
    { q: 'Which of these is the strongest password?',
      o: ['A long passphrase like three random words', 'Your pet\'s name', 'Password1', 'Your date of birth'], a: 0,
      e: 'Length beats complexity. Three random words make a long password that is hard to guess but easy to remember.' },
    { q: 'What does multi-factor authentication (MFA) add on top of your password?',
      o: ['A second check, like a code or app approval', 'A longer password', 'A faster login', 'A new username'], a: 0,
      e: 'MFA means even if someone steals your password, they still cannot get in without the second factor.' },
    { q: 'Should you use the same password for every account?',
      o: ['No, use a different one for each', 'Yes, it is easier', 'Only for work accounts', 'Only for email'], a: 0,
      e: 'If one site is breached, reused passwords let attackers into all your other accounts.' },
    { q: 'What is the safest way to keep track of lots of strong passwords?',
      o: ['A password manager', 'A sticky note on your monitor', 'A text file called "passwords"', 'Using the same one everywhere'], a: 0,
      e: 'A password manager creates and stores unique strong passwords, so you only remember one master password.' },
    { q: 'A website offers "Sign in with Google/Microsoft". Is that generally safe to use?',
      o: ['Yes, it avoids making another password', 'No, never use it', 'Only on your phone', 'Only once a year'], a: 0,
      e: 'Single sign-on means one fewer password to manage, backed by that provider\'s security and MFA.' },
    { q: 'Someone phones claiming to be IT and asks for your password. What do you do?',
      o: ['Refuse - real IT never needs your password', 'Give it to them', 'Give them half of it', 'Email it instead'], a: 0,
      e: 'Legitimate IT staff can reset or access systems without your password. Asking for it is a red flag.' },
    { q: 'Your password may have been in a data breach. What should you do?',
      o: ['Change it, and anywhere you reused it', 'Nothing', 'Wait a year', 'Make it one character longer'], a: 0,
      e: 'Change the breached password straight away, and change it anywhere else you used the same one.' },
    { q: 'Is it a good idea to write your PIN on the back of your bank card?',
      o: ['No, keep it separate and secret', 'Yes, so you remember it', 'Only in pencil', 'Only for a new card'], a: 0,
      e: 'A card and its PIN together is all a thief needs. Keep the PIN in your head, not on the card.' },
    { q: 'What makes a security question like "mother\'s maiden name" risky?',
      o: ['The answer is often easy to find online', 'It is too long', 'It is too short', 'It uses numbers'], a: 0,
      e: 'Answers to common security questions can often be found on social media, so treat them like passwords.' },
    { q: 'Your screen will be unattended for a few minutes. What should you do?',
      o: ['Lock it (Windows key + L)', 'Leave it open', 'Turn the monitor off only', 'Minimise everything'], a: 0,
      e: 'Locking your screen stops anyone walking past from using your logged-in session.' },
    { q: 'A site says your new password cannot be a previous one. Why is that good?',
      o: ['It stops you reusing a possibly-leaked old password', 'It makes the site faster', 'It saves storage', 'It is just annoying'], a: 0,
      e: 'Reusing an old password that may already be exposed would undo the point of changing it.' },
    { q: 'Best way to share a password with a colleague who genuinely needs it?',
      o: ['Use a password manager\'s secure share, or avoid sharing', 'Email it', 'Text it', 'Say it across the office'], a: 0,
      e: 'Shared logins are risky; where unavoidable, use a password manager\'s secure sharing, never plain email or chat.' }
  ],

  // ---------- The Pit: Phishing & Scams ----------
  pit: [
    { q: 'What is "phishing"?',
      o: ['A fake message that tricks you into giving away info', 'A type of firewall', 'A password manager', 'A software update'], a: 0,
      e: 'Phishing messages pretend to be from someone you trust to steal passwords, money or data.' },
    { q: 'An email says "Your account will be closed in 1 hour - click here now!". What is the warning sign?',
      o: ['Urgency and pressure to act fast', 'It mentions your account', 'It is an email', 'It has a subject line'], a: 0,
      e: 'Creating panic so you act without thinking is a classic phishing tactic. Slow down and check.' },
    { q: 'How can you check where a link really goes before clicking?',
      o: ['Hover over it to see the real address', 'Click it quickly', 'Forward it to a friend', 'Reply asking if it is safe'], a: 0,
      e: 'Hovering (or long-pressing on mobile) shows the true destination, which often differs from the text.' },
    { q: 'You get an unexpected invoice attachment from an unknown sender. What do you do?',
      o: ['Do not open it; verify first', 'Open it to see what it is', 'Enable editing and macros', 'Reply "who are you?"'], a: 0,
      e: 'Unexpected attachments can carry malware. Confirm with the supposed sender through a known contact method.' },
    { q: 'A text message says you missed a parcel and must pay a small fee via a link. Likely...',
      o: ['A scam ("smishing")', 'A real courier', 'A bank update', 'A software patch'], a: 0,
      e: 'Fake delivery texts are extremely common. Go to the courier\'s official site directly, never the link.' },
    { q: 'What is the safest response to a suspicious email at work?',
      o: ['Report it to IT / security', 'Delete it quietly', 'Forward it to colleagues to warn them', 'Click to unsubscribe'], a: 0,
      e: 'Reporting lets your security team block it for everyone. Clicking "unsubscribe" can confirm your address is live.' },
    { q: 'An email from your "CEO" urgently asks you to buy gift cards. This is...',
      o: ['A business email compromise scam', 'Normal', 'A bonus scheme', 'A tax rule'], a: 0,
      e: 'Attackers impersonate bosses to rush staff into buying gift cards or moving money. Verify in person or by phone.' },
    { q: 'The sender address is "support@paypa1.com" instead of paypal.com. What happened?',
      o: ['A look-alike domain to fool you', 'A typo that is fine', 'A faster server', 'A new PayPal brand'], a: 0,
      e: 'Attackers register look-alike domains (here a "1" for an "l"). Always check the exact spelling.' },
    { q: 'A pop-up says "Your PC is infected! Call this number now." You should...',
      o: ['Ignore it and close the browser', 'Call the number', 'Enter your card to "fix" it', 'Install what it offers'], a: 0,
      e: 'This is tech-support scareware. Never call the number or install anything; just close the browser.' },
    { q: 'Why do attackers use QR codes in phishing ("quishing")?',
      o: ['You cannot easily see where they lead', 'They are faster', 'They are free', 'They look official'], a: 0,
      e: 'A QR code hides its destination. Be as cautious with unexpected QR codes as with unexpected links.' },
    { q: 'An email greeting says "Dear Valued Customer" instead of your name. This can be...',
      o: ['A sign of a mass phishing email', 'Always genuine', 'A delivery receipt', 'A security upgrade'], a: 0,
      e: 'Generic greetings suggest a message blasted to many people. It is one clue among several to check.' },
    { q: 'You clicked a phishing link and entered your password. What now?',
      o: ['Change that password and tell IT immediately', 'Hope for the best', 'Turn off your monitor', 'Wait to see if anything happens'], a: 0,
      e: 'Act fast: change the password (and reused ones) and report it so IT can watch for misuse.' }
  ],

  // ---------- Spinner 1: Safe Browsing ----------
  spinner1: [
    { q: 'The padlock / "https" in your browser means...',
      o: ['The connection is encrypted', 'The site is honest', 'The site is a bank', 'The site is virus-free'], a: 0,
      e: 'HTTPS encrypts traffic in transit. It does NOT prove the site itself is trustworthy - scam sites use it too.' },
    { q: 'You want to visit your bank. Safest way to get there?',
      o: ['Type the address or use a saved bookmark', 'Click a link in an email', 'Search and click the first ad', 'Follow a link from social media'], a: 0,
      e: 'Typing it yourself or using your own bookmark avoids fake look-alike sites and malicious ads.' },
    { q: 'Public free Wi-Fi in a cafe is...',
      o: ['Convenient but less private - avoid sensitive logins', 'Completely safe', 'Faster than home', 'Encrypted for you'], a: 0,
      e: 'Others may snoop on open Wi-Fi. Use your mobile data or a VPN for anything sensitive.' },
    { q: 'A download site offers a "free" copy of paid software. The risk is...',
      o: ['It may be bundled with malware', 'It is too slow', 'It is illegal only', 'Nothing', ], a: 0,
      e: 'Cracked or "free" paid software is a very common way to spread malware. Get software from official sources.' },
    { q: 'A browser extension asks to "read and change all your data on all websites". You should...',
      o: ['Be cautious - only install trusted, needed ones', 'Always allow it', 'Install several to be safe', 'Ignore the warning'], a: 0,
      e: 'Powerful permissions can read your passwords and pages. Install few extensions, from reputable publishers.' },
    { q: 'Your browser warns "Your connection is not private". You should...',
      o: ['Not continue to the site', 'Click through anyway', 'Turn off the warning', 'Restart the router'], a: 0,
      e: 'That warning can mean an expired certificate or an interception. Don\'t enter data on a warned site.' },
    { q: 'What does a VPN mainly do for you on untrusted Wi-Fi?',
      o: ['Encrypts your traffic through a secure tunnel', 'Makes you anonymous to everyone', 'Removes all viruses', 'Speeds up every site'], a: 0,
      e: 'A VPN encrypts your connection so local snoopers can\'t read it. It is not total anonymity or antivirus.' },
    { q: '"Cookies" on websites are...',
      o: ['Small files that remember things like your login', 'Always spyware', 'Computer viruses', 'A type of password'], a: 0,
      e: 'Cookies store small bits of data. Most are harmless (logins, settings); some track you across sites.' },
    { q: 'A site you\'ve never used emails "click to claim your prize". Best action?',
      o: ['Delete it - you didn\'t enter any prize draw', 'Claim the prize', 'Enter your details to check', 'Forward to friends'], a: 0,
      e: 'Unexpected "you\'ve won" messages are bait. If you didn\'t enter, there is no prize.' },
    { q: 'Keeping your browser up to date mainly...',
      o: ['Fixes security holes attackers exploit', 'Changes the colour', 'Adds more ads', 'Slows it down'], a: 0,
      e: 'Updates patch known vulnerabilities. An out-of-date browser is an easy target.' },
    { q: 'An online shop has no contact details, poor spelling and prices too good to be true. Likely...',
      o: ['A scam shop', 'A great bargain', 'A new brand', 'A charity'], a: 0,
      e: 'Fake shops take your money or card details. Check reviews and use a card with buyer protection.' },
    { q: 'Autofill saved your card in the browser. On a shared/public PC this is...',
      o: ['Risky - don\'t save card details there', 'Fine', 'Encrypted and safe', 'Required'], a: 0,
      e: 'On a shared computer, saved cards and logins are available to the next user. Never save them there.' }
  ],

  // ---------- Spinner 2: Devices & Updates ----------
  spinner2: [
    { q: 'Why should you install software updates reasonably promptly?',
      o: ['They fix security flaws', 'They use more battery', 'They cost money', 'They are optional forever'], a: 0,
      e: 'Many attacks exploit flaws that updates have already fixed. Patching closes the door.' },
    { q: 'What is the main job of antivirus / endpoint protection?',
      o: ['Detect and block malicious software', 'Make the PC faster', 'Back up your files', 'Manage passwords'], a: 0,
      e: 'It spots and stops known malware and suspicious behaviour. It\'s one layer, not the only one.' },
    { q: 'You find a USB stick in the car park. What do you do?',
      o: ['Hand it to IT / don\'t plug it in', 'Plug it in to find the owner', 'Take it home to use', 'Plug it into a work PC'], a: 0,
      e: 'Dropped USB sticks are a known attack. Plugging one in can infect your machine instantly.' },
    { q: 'Backups protect you against ransomware and loss. A good backup is...',
      o: ['Recent, tested, and kept offline/separate', 'On the same drive as the files', 'Never tested', 'A screenshot'], a: 0,
      e: 'A backup you can actually restore, kept separate from the originals, is your safety net.' },
    { q: 'Your phone offers a security update. You should...',
      o: ['Install it soon', 'Ignore it forever', 'Only if the phone is new', 'Only on Wi-Fi once a year'], a: 0,
      e: 'Phones hold huge amounts of personal data. Keep the OS and apps updated.' },
    { q: 'An app wants access to your contacts, camera, mic and location but it\'s just a torch. You should...',
      o: ['Deny permissions it doesn\'t need', 'Grant everything', 'Uninstall your antivirus', 'Trust it'], a: 0,
      e: 'Apps should only get the access they genuinely need. Over-asking is a privacy red flag.' },
    { q: 'What does encrypting your laptop/phone protect against?',
      o: ['Someone reading your data if it\'s lost or stolen', 'Viruses', 'Phishing emails', 'Slow Wi-Fi'], a: 0,
      e: 'Full-disk encryption means a thief with the device still can\'t read your files without your login.' },
    { q: 'Old software that no longer gets security updates ("end of life") is...',
      o: ['Risky - flaws stay unpatched', 'Safer because it\'s stable', 'Faster', 'Fine forever'], a: 0,
      e: 'Once support ends, new flaws are never fixed. Upgrade or replace end-of-life software.' },
    { q: 'Where should you get mobile apps from?',
      o: ['The official app store', 'Any website offering the file', 'Links in texts', 'Email attachments'], a: 0,
      e: 'Official stores vet apps. Side-loaded apps from random sites are a common malware route.' },
    { q: 'A "free" public phone charging port could in theory...',
      o: ['Carry data, not just power ("juice jacking")', 'Charge faster', 'Clean your phone', 'Update your apps'], a: 0,
      e: 'Use your own charger and plug, or a charge-only cable, with unknown public USB ports.' },
    { q: 'You\'re disposing of an old laptop. Before you do, you should...',
      o: ['Securely wipe or destroy the drive', 'Just delete your files', 'Empty the recycle bin', 'Nothing'], a: 0,
      e: 'Deleted files can be recovered. Use a secure wipe or physically destroy the drive.' },
    { q: 'Default admin passwords on a new router or device should be...',
      o: ['Changed immediately', 'Left as-is', 'Written on the device', 'Shared online'], a: 0,
      e: 'Default passwords are public knowledge. Change them before putting any device online.' }
  ],

  // ---------- Spinner 3: Data & Privacy ----------
  spinner3: [
    { q: 'What counts as "personal data"?',
      o: ['Anything that identifies a living person', 'Only passwords', 'Only bank details', 'Only medical records'], a: 0,
      e: 'Name, email, address, photos and more can identify someone - all personal data to protect.' },
    { q: 'You get an email with 50 colleagues\' addresses all in the To/Cc field. The problem?',
      o: ['It exposed everyone\'s address - use Bcc', 'The font is wrong', 'It\'s too long', 'Nothing'], a: 0,
      e: 'Putting many external recipients in Cc leaks their addresses to all. Use Bcc for group emails.' },
    { q: 'Oversharing on social media (holidays, pets, workplace) can help attackers...',
      o: ['Guess passwords and craft targeted scams', 'Nothing at all', 'Only annoy you', 'Improve your privacy'], a: 0,
      e: 'Details you post can answer security questions or make phishing more convincing. Share thoughtfully.' },
    { q: 'If you handle customer data, you should only access it...',
      o: ['When you have a genuine business need', 'Whenever you\'re curious', 'To look up friends', 'For fun'], a: 0,
      e: 'Looking up data without a legitimate reason breaks privacy rules and trust, even if you can technically see it.' },
    { q: 'Before sending a spreadsheet externally, you should check...',
      o: ['For hidden rows, tabs and extra personal data', 'The font colour', 'The file name only', 'Nothing'], a: 0,
      e: 'Files often carry more than you think - hidden tabs, comments, extra columns. Review before sharing.' },
    { q: 'A stranger "tailgates" through a secure door behind you. You should...',
      o: ['Politely challenge or ask them to badge in', 'Hold the door and smile', 'Ignore it', 'Give them your badge'], a: 0,
      e: 'Tailgating bypasses physical security. It\'s okay to ask who someone is or direct them to reception.' },
    { q: 'The safest place to store sensitive work files is...',
      o: ['Approved company systems', 'Your personal cloud drive', 'A USB stick in your bag', 'Your personal email'], a: 0,
      e: 'Company-approved storage is backed up and secured. Personal accounts and USB sticks aren\'t controlled.' },
    { q: 'Printing something confidential on a shared printer - what\'s the risk?',
      o: ['Others may pick it up', 'It wastes ink', 'It\'s too slow', 'Nothing'], a: 0,
      e: 'Confidential prints left on a tray can be seen or taken. Use secure/held print and collect promptly.' },
    { q: 'Someone shoulder-surfs as you type a password on the train. A defence is...',
      o: ['A privacy screen and awareness of surroundings', 'Typing faster', 'Turning up the brightness', 'Reading aloud'], a: 0,
      e: 'Be aware of who can see your screen; privacy filters make it hard to read from an angle.' },
    { q: 'You no longer need a document full of personal data. You should...',
      o: ['Dispose of it securely (shred / secure delete)', 'Put it in the recycling bin', 'Leave it on your desk', 'Email it to yourself'], a: 0,
      e: 'Securely destroy data you no longer need - shred paper, securely delete files.' },
    { q: '"Least privilege" means people should have...',
      o: ['Only the access their job needs', 'Admin rights for everyone', 'No access at all', 'Access to everything just in case'], a: 0,
      e: 'Limiting access reduces damage if an account is misused or compromised.' },
    { q: 'If you spot a possible data breach at work, you should...',
      o: ['Report it quickly to the right team', 'Keep quiet to avoid trouble', 'Fix it secretly', 'Post about it online'], a: 0,
      e: 'Fast reporting limits harm and is usually a legal requirement. Raising it is the right thing to do.' }
  ],

  // ---------- MEGA SPIN: Boss - Staying Safe ----------
  mega: [
    { q: 'BOSS: What is "ransomware"?',
      o: ['Malware that locks your files and demands payment', 'A password manager', 'A firewall', 'A backup tool'], a: 0,
      e: 'Ransomware encrypts your data and demands a ransom. Good, tested, offline backups are the best defence.' },
    { q: 'BOSS: What is "social engineering"?',
      o: ['Tricking people into breaking security', 'Building social networks', 'A coding language', 'A type of cable'], a: 0,
      e: 'Social engineering targets people, not just computers - manipulation to get access, data or money.' },
    { q: 'BOSS: Which is the best overall summary of good MFA?',
      o: ['Something you know + something you have/are', 'Two passwords', 'A longer username', 'A password written down twice'], a: 0,
      e: 'Strong MFA combines factors of different types, e.g. a password plus a phone app or fingerprint.' },
    { q: 'BOSS: A colleague\'s account starts sending odd emails. Most likely...',
      o: ['Their account is compromised - report it', 'They changed email style', 'A font update', 'Nothing to worry about'], a: 0,
      e: 'Unusual messages from a known account often mean it\'s been taken over. Report so it can be secured.' },
    { q: 'BOSS: Why are app-based or hardware MFA codes better than SMS codes?',
      o: ['SMS can be intercepted or SIM-swapped', 'SMS is too slow', 'SMS costs more', 'They look nicer'], a: 0,
      e: 'Text codes can be intercepted or stolen via SIM-swap. Authenticator apps and security keys are stronger.' },
    { q: 'BOSS: The main point of a firewall is to...',
      o: ['Control what network traffic is allowed in/out', 'Scan email for spelling', 'Store passwords', 'Back up files'], a: 0,
      e: 'A firewall filters network connections, blocking unwanted traffic by rules.' },
    { q: 'BOSS: "Zero trust" roughly means...',
      o: ['Verify every request, trust nothing by default', 'Trust everyone inside the office', 'No passwords needed', 'Block the internet'], a: 0,
      e: 'Zero trust assumes no user or device is automatically trusted - each access is verified.' },
    { q: 'BOSS: A strong incident response starts with...',
      o: ['Reporting quickly so the team can act', 'Hiding the problem', 'Turning everything off at random', 'Blaming someone'], a: 0,
      e: 'Early reporting lets responders contain damage. A no-blame culture gets issues raised sooner.' },
    { q: 'BOSS: Why patch quickly after a vulnerability is made public?',
      o: ['Attackers rush to exploit known, unpatched flaws', 'Patches expire', 'It\'s the law to patch hourly', 'To change the UI'], a: 0,
      e: 'Once a flaw is public, exploitation attempts spike. Prompt patching shrinks the window of risk.' },
    { q: 'BOSS: A deepfake voice call pretends to be your manager. A good control is...',
      o: ['Verify via a known, separate channel', 'Do whatever the voice says', 'Call the number it gives you', 'Ignore all calls forever'], a: 0,
      e: 'AI can now fake voices. For unusual requests, confirm through a trusted channel you already know.' },
    { q: 'BOSS: The best cyber security overall is...',
      o: ['Layers: people, process and technology together', 'One perfect product', 'Just antivirus', 'Just a strong password'], a: 0,
      e: 'No single tool is enough. Defence in depth combines aware people, good processes and technology.' },
    { q: 'BOSS: Reporting a phishing email you ALMOST fell for is...',
      o: ['Helpful - it protects everyone else', 'Embarrassing, so stay quiet', 'Pointless', 'Against the rules'], a: 0,
      e: 'Near-misses are valuable warnings. Reporting helps block the threat for the whole organisation.' }
  ]
};
